  
version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "mypassword"
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0-beta.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mypassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "adminsecret"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
volumes:
  db_data:
